# [relaychain]
# default_command = "polkadot"
# chain = "rococo-local"

# [[relaychain.nodes]]
# name = "alice"
# validator = true
# ws_port = 9944

# [[relaychain.nodes]]
# name = "bob"
# validator = true
# ws_port = 9955

# [[parachains]]
# id = 1000
# chain_spec_path = "./dev_chain_spec.json"

# [parachains.collator]
# name = "charlie"
# ws_port = 9988
# command = "polkadot-omni-node"


[relaychain]
default_command = "polkadot-omni-node"
chain = "dev"
chain_spec_path = "./dev_chain_spec.json"
default_args = ["--dev-block-time 3000"]

[[relaychain.nodes]]
name = "alice"
ws_port = 9944